wheel:
  mass: 0.01        # Wheel mass in Kg
  radius: 0.0331    # Wheel radius in m
  length: 0.025     # Wheel length in m, considering is as a cylinder
  mesh: 'wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
  #mesh: ''
  x_offset: 0.079
  y_offset: 0.015
  z_offset: -0.017
